on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: quentindecosne/sunlit@v1.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
